/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Design System Colors dari Theme
        'secondary-fixed': '#dee3eb',
        'error-container': '#93000a',
        'tertiary': '#c3c7cd',
        'on-secondary-fixed-variant': '#42474e',
        'tertiary-container': '#8d9197',
        'inverse-on-surface': '#313030',
        'primary-container': '#dc2626',
        'background': '#131313',
        'on-secondary': '#2c3137',
        'secondary': '#c2c7cf',
        'primary-fixed': '#fecaca',
        'inverse-surface': '#e5e2e1',
        'on-secondary-fixed': '#171c22',
        'on-secondary-container': '#b4b9c1',
        'on-surface': '#e5e2e1',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'surface-variant': '#353534',
        'secondary-fixed-dim': '#c2c7cf',
        'on-tertiary-fixed-variant': '#43474c',
        'surface-container-high': '#2a2a2a',
        'on-primary': '#7f1d1d',
        'on-primary-container': '#991b1b',
        'on-tertiary': '#2c3136',
        'secondary-container': '#444a50',
        'on-error-container': '#ffdad6',
        'inverse-primary': '#b91c1c',
        'surface-tint': '#ef4444',
        'surface': '#131313',
        'tertiary-fixed-dim': '#c3c7cd',
        'surface-container': '#201f1f',
        'on-tertiary-container': '#252a2f',
        'primary-fixed-dim': '#fca5a5',
        'surface-container-low': '#1c1b1b',
        'surface-container-highest': '#353534',
        'on-background': '#e5e2e1',
        'surface-dim': '#131313',
        'outline': '#b91c1c',
        'on-primary-fixed': '#450a0a',
        'primary': '#ef4444',
        'surface-container-lowest': '#0e0e0e',
        'on-surface-variant': '#fca5a5',
        'tertiary-fixed': '#dfe3e9',
        'outline-variant': '#7f1d1d',
        'surface-bright': '#393939',
        'on-tertiary-fixed': '#171c20',
        'on-primary-fixed-variant': '#b91c1c',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #ef4444 0%, #dc2626 100%)',
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out forwards',
        'fade-in-down': 'fadeInDown 0.8s ease-out forwards',
        'zoom-in': 'zoomIn 0.5s ease-out forwards',
        'float': 'float 3s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'slide-up': 'slideUp 0.7s ease-out forwards',
        'scale-in': 'scaleIn 0.5s ease-out forwards',
        'shimmer': 'shimmer 2s infinite',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        fadeInDown: {
          from: { opacity: '0', transform: 'translateY(-40px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        zoomIn: {
          from: { opacity: '0', transform: 'scale(0.9)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(239, 68, 68, 0.3)' },
          '50%': { boxShadow: '0 0 40px rgba(239, 68, 68, 0.6)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(50px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          from: { opacity: '0', transform: 'scale(0.8)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
