import { NextResponse } from 'next/server';
import { getDatabase, ref, get } from 'firebase/database';
import { db } from '@/lib/firebase';

export const dynamic = 'force-dynamic';

export async function GET() {
  try {
    // Fetch SEO settings from Firebase
    const seoRef = ref(db, 'seo');
    const snapshot = await get(seoRef);
    const seoData = snapshot.val();

    const baseUrl = seoData?.siteUrl || 'https://atmautolighting.com';
    const allowRobots = seoData?.robotsAllow !== false;
    const customRules = seoData?.robotsCustomRules || '';

    // Build robots.txt content
    let content = `# Robots.txt for ${baseUrl}
# Generated by ATM Autolighting SEO System

User-agent: *
`;

    if (allowRobots) {
      content += `
# Allow all crawling
Allow: /

# Sitemap location
Sitemap: ${baseUrl}/sitemap.xml

# Crawl-delay (optional)
Crawl-delay: 1

# Disallow admin and private areas
Disallow: /admin/
Disallow: /api/
Disallow: /_next/
Disallow: /*?*

# Allow specific paths
Allow: /products
Allow: /about
Allow: /product/*

# Common bot rules
User-agent: Googlebot
Allow: /
Disallow: /admin/
Disallow: /api/

User-agent: Googlebot-Image
Allow: /
Disallow: /admin/

User-agent: Bingbot
Allow: /
Disallow: /admin/

User-agent: Slurp
Allow: /
Disallow: /admin/

User-agent: DuckDuckBot
Allow: /
Disallow: /admin/

User-agent: Baiduspider
Allow: /
Disallow: /admin/

User-agent: YandexBot
Allow: /
Disallow: /admin/

User-agent: facebot
Allow: /
Disallow: /admin/

User-agent: ia_archiver
Allow: /
Disallow: /admin/

User-agent: Twitterbot
Allow: /
Disallow: /admin/

# Block bad bots
User-agent: AhrefsBot
Disallow: /

User-agent: SemrushBot
Disallow: /

User-agent: MJ12bot
Disallow: /

User-agent: Exabot
Disallow: /

User-agent: CCBot
Disallow: /
`;
    } else {
      content += `
# Site is not allowed to be indexed
Disallow: /

# Allow only essential resources
Allow: /favicon.ico
Allow: /apple-touch-icon.png
`;
    }

    // Add custom rules if defined
    if (customRules) {
      content += `
# Custom rules
${customRules}
`;
    }

    content += `
# Host (optional, for Yandex)
Host: ${baseUrl}

# Generated on: ${new Date().toISOString()}
`;

    return new NextResponse(content, {
      headers: {
        'Content-Type': 'text/plain',
        'Cache-Control': 'public, s-maxage=86400',
      },
    });
  } catch (error) {
    console.error('Error generating robots.txt:', error);
    
    // Return default robots.txt as fallback
    const content = `# Robots.txt
User-agent: *
Allow: /

Sitemap: https://atmautolighting.com/sitemap.xml
`;

    return new NextResponse(content, {
      headers: {
        'Content-Type': 'text/plain',
      },
    });
  }
}
